apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pg
spec:
  storageClassName: manual-pg
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbit
spec:
  storageClassName: manual-rabbit
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-art
spec:
  storageClassName: manual-art
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-xray
spec:
  storageClassName: manual-xray
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
