apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pg
  labels:
    type: local
spec:
  storageClassName: manual-pg
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${HOST_PATH}/pg
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbit
  labels:
    type: local
spec:
  storageClassName: manual-rabbit
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${HOST_PATH}/rabbit
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-art
  labels:
    type: local
spec:
  storageClassName: manual-art
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${HOST_PATH}/art
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-xray
  labels:
    type: local
spec:
  storageClassName: manual-xray
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${HOST_PATH}/xray








